# Merging:
# https://stackoverflow.com/questions/73498168/github-actions-merge-artifacts-after-matrix-steps

name: Release

on:
  workflow_dispatch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
env:
  python-version: "3.9"

jobs:
  python-package:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools build
        pip install -r requirements.txt
    - name: Build package
      run: |
        python -m build
        echo "WHEEL_NAME=$(find ./dist/*.whl -maxdepth 1 -type f -printf '%f\n' | tail -n 1)" >> "$GITHUB_ENV"
        echo "LIBGARIB_VERSION=$(cd python && python -c 'import libgarib as l; print(l.__version__)')" >> "$GITHUB_ENV"
    - name: Freeze tools
      run: |
        python -m pip install dist/${{ env.WHEEL_NAME }} pyinstaller
        pyinstaller -y --clean tools/tools.spec
    - name: Archive python package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.WHEEL_NAME }}
        path: dist/${{ env.WHEEL_NAME }}
    - name: Archive tools
      uses: actions/upload-artifact@v4
      with:
        name: libgarib-tools-${{ env.LIBGARIB_VERSION }}-${{ matrix.os }}
        path: |
          dist/tools
