# Merging:
# https://stackoverflow.com/questions/73498168/github-actions-merge-artifacts-after-matrix-steps

name: Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  python-version: "3.11"

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools build
        pip install -r requirements.txt
    - name: Install Kaitai Struct compiler
      run: |
        wget https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.10/kaitai-struct-compiler-0.10.zip
        unzip kaitai-struct-compiler-0.10.zip
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo "KAITAI_BIN=$(realpath kaitai-struct-compiler-0.10/bin/kaitai-struct-compiler.bat)" >> "$GITHUB_ENV"
        else
          echo "KAITAI_BIN=$(realpath kaitai-struct-compiler-0.10/bin/kaitai-struct-compiler)" >> "$GITHUB_ENV"
        fi
    - name: Build package
      run: |
        make clean parsers
        python -m build
    - name: Recover build metadata
      run: |
        WHEEL_NAME=$(cd dist && ls *.whl | tail -n 1)
        echo "WHEEL_NAME=$WHEEL_NAME" >> "$GITHUB_ENV"
        echo "LIBGARIB_VERSION=$(IFS='-'; arr=($WHEEL_NAME); unset IFS; echo ${arr[1]})" >> "$GITHUB_ENV"
    - name: Freeze tools
      run: |
        python -m pip install dist/${{ env.WHEEL_NAME }} pyinstaller
        pyinstaller -y --clean tools/tools.spec
    - name: Archive python package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.WHEEL_NAME }}
        path: dist/${{ env.WHEEL_NAME }}
    - name: Archive tools
      uses: actions/upload-artifact@v4
      with:
        name: libgarib-tools-${{ env.LIBGARIB_VERSION }}-${{ matrix.os }}
        path: |
          dist/tools
